# Generated by Django 4.0.2 on 2022-02-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_product_image3_product_image4_alter_product_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stocks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
