# Generated by Django 4.0.2 on 2022-02-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_product_stocks_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prize',
            new_name='price',
        ),
    ]
