# Generated by Django 4.0.2 on 2022-02-28 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0008_pricetype_product_ptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='btype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Adminapp.brand'),
        ),
    ]
