# Generated by Django 4.0.2 on 2022-03-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0009_brand_product_btype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
