# Generated by Django 4.0.2 on 2022-03-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0011_product_offerpercent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offerbuycount',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
