# Generated by Django 4.0.2 on 2022-03-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0014_alter_catogery_catpercent_alter_product_offerpercent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlist',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
