# Generated by Django 4.0.2 on 2022-03-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0015_product_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wishlist',
        ),
    ]
