# Generated by Django 4.0.2 on 2022-02-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='propic',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
