# Generated by Django 4.0.2 on 2022-02-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0011_users_propic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='propic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
