# Generated by Django 4.0.2 on 2022-02-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0017_alter_address_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
