# Generated by Django 4.0.2 on 2022-02-24 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0020_remove_order_payment_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default=0, max_length=30)),
                ('method', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('None', 'None'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='None', max_length=30)),
                ('transactionid', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Userapp.order')),
            ],
        ),
    ]
