# Generated by Django 4.0.2 on 2022-03-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0023_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Placed', 'Placed'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Return', 'Return')], default='New', max_length=200, null=True),
        ),
    ]
