# Generated by Django 4.0.2 on 2022-03-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0025_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
