# Generated by Django 4.0.2 on 2022-03-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0026_remove_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='amount',
            field=models.FloatField(),
        ),
    ]
