# Generated by Django 4.0.2 on 2022-03-04 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0027_alter_pay_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='payuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
