# Generated by Django 4.0.2 on 2022-03-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0028_pay_payuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='propic',
            field=models.ImageField(blank=True, default='2950f96af23e53d8ba98351184c2c803_eW7MOkE.jpg', null=True, upload_to='images'),
        ),
    ]
