# Generated by Django 4.0.2 on 2022-03-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0029_alter_users_propic'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='device',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
