# Generated by Django 4.0.2 on 2022-03-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0030_users_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='device',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
