# Generated by Django 4.0.2 on 2022-03-08 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0032_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.CharField(max_length=30)),
                ('offer_percentage', models.FloatField(default=0, max_length=30)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('use_count', models.FloatField(default=0, max_length=30)),
                ('total_lessed_money', models.FloatField(default=0, max_length=30)),
                ('active', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UseCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False)),
                ('lessed_money', models.FloatField(default=0, max_length=30)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Userapp.coupondetail')),
                ('fororder', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Userapp.order')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
