# Generated by Django 4.0.2 on 2022-03-09 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0035_order_coupon_used'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UseCoupon',
            new_name='CouponUsed',
        ),
    ]
