# Generated by Django 4.0.2 on 2022-03-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0036_rename_usecoupon_couponused'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupondetail',
            name='applied',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
