# Generated by Django 4.0.2 on 2022-03-13 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0040_order_offer_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponused',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
