# Generated by Django 4.0.2 on 2022-03-14 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0016_remove_product_wishlist'),
        ('Userapp', '0041_alter_couponused_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productadded', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.product')),
                ('useradded', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
